/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package annuaire.view;

import annuaire.controleur.controleurPersonne;
import annuaire.dao.daoPersonne;
import annuaire.metier.Personne;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author anthony
 */
public class FrameSupprimerPersonne extends javax.swing.JFrame {
        daoPersonne dao = new daoPersonne(); 
        ArrayList<Personne> lb = new ArrayList<Personne>();
        private int i = 0;
        private long numPersonne;
        private String nom_pers,prenom_pers,email_pers,date_naiss,organisation,observations;
        int max;
        
        /**
     * Creates new form FrameModifierPersonne
     */
    public FrameSupprimerPersonne() {
        lb = dao.getALL();
        this.numPersonne = lb.get(0).getNumPers();
        this.nom_pers = lb.get(0).getNomPers();
        this.prenom_pers = lb.get(0).getPrenomPers();
        this.email_pers = lb.get(0).getEmailPers();
        this.date_naiss = lb.get(0).getDateNaissancePers();
        this.organisation = lb.get(0).getOrganisationPers();
        this.observations = lb.get(0).getObservationPers();
        this.max = lb.size();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panModifierPersonne = new javax.swing.JPanel();
        lblSupprimerPersonne = new javax.swing.JLabel();
        btnFermerFenetre = new javax.swing.JButton();
        lblIdPersonne = new javax.swing.JLabel();
        txtIdPersonne = new javax.swing.JTextField(String.valueOf(numPersonne));
        lblNomPersonne = new javax.swing.JLabel();
        txtNomPersonne = new javax.swing.JTextField(nom_pers);
        lblPrenomPersonne = new javax.swing.JLabel();
        txtPrenomPersonne = new javax.swing.JTextField(prenom_pers);
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField(email_pers);
        lblDateNaissance = new javax.swing.JLabel();
        txtDateNaissance = new javax.swing.JTextField(date_naiss);
        lblOrganisation = new javax.swing.JLabel();
        txtOrganisation = new javax.swing.JTextField(organisation);
        lblObservations = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaObservations = new javax.swing.JTextArea(observations);
        btnSuivant = new javax.swing.JButton();
        btnPrecedent = new javax.swing.JButton();
        lblCompteur = new javax.swing.JLabel();
        lblCompteurTotal = new javax.swing.JLabel();
        lblSeparateur = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panModifierPersonne.setBackground(new java.awt.Color(153, 0, 153));

        lblSupprimerPersonne.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblSupprimerPersonne.setForeground(new java.awt.Color(255, 255, 255));
        lblSupprimerPersonne.setText("Supprimer Personne");

        btnFermerFenetre.setText("Fermer cette fenêtre");
        btnFermerFenetre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerFenetreActionPerformed(evt);
            }
        });

        lblIdPersonne.setText("Id personne :");

        txtIdPersonne.setEditable(false);

        lblNomPersonne.setText("Nom :");

        txtNomPersonne.setEditable(false);

        lblPrenomPersonne.setText("Prénom :");

        txtPrenomPersonne.setEditable(false);

        lblEmail.setText("Email :");

        txtEmail.setEditable(false);

        lblDateNaissance.setText("Date de naissance :");

        txtDateNaissance.setEditable(false);

        lblOrganisation.setText("Organisation :");

        txtOrganisation.setEditable(false);

        lblObservations.setText("Observations :");

        txtaObservations.setEditable(false);
        txtaObservations.setColumns(20);
        txtaObservations.setRows(5);
        jScrollPane1.setViewportView(txtaObservations);

        btnSuivant.setText("Suivant");
        btnSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantActionPerformed(evt);
            }
        });

        btnPrecedent.setText("Précédent");
        btnPrecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecedentActionPerformed(evt);
            }
        });

        lblCompteur.setText("1");

        lblCompteurTotal.setText(String.valueOf(this.max));

        lblSeparateur.setText("/");

        btnDelete.setText("Supprimer");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panModifierPersonneLayout = new javax.swing.GroupLayout(panModifierPersonne);
        panModifierPersonne.setLayout(panModifierPersonneLayout);
        panModifierPersonneLayout.setHorizontalGroup(
            panModifierPersonneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panModifierPersonneLayout.createSequentialGroup()
                .addGroup(panModifierPersonneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panModifierPersonneLayout.createSequentialGroup()
                        .addGroup(panModifierPersonneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panModifierPersonneLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(panModifierPersonneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panModifierPersonneLayout.createSequentialGroup()
                                        .addGroup(panModifierPersonneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblEmail)
                                            .addComponent(lblDateNaissance)
                                            .addComponent(lblPrenomPersonne)
                                            .addComponent(lblNomPersonne)
                                            .addComponent(lblIdPersonne)
                                            .addComponent(lblOrganisation))
                                        .addGap(62, 62, 62)
                                        .addGroup(panModifierPersonneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNomPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIdPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPrenomPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panModifierPersonneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtOrganisation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                                .addComponent(txtDateNaissance, javax.swing.GroupLayout.Alignment.LEADING))))
                                    .addGroup(panModifierPersonneLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panModifierPersonneLayout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(lblObservations)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panModifierPersonneLayout.createSequentialGroup()
                        .addGroup(panModifierPersonneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panModifierPersonneLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(lblSupprimerPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCompteur)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSeparateur))
                            .addGroup(panModifierPersonneLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnPrecedent)
                                .addGap(30, 30, 30)
                                .addGroup(panModifierPersonneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDelete)
                                    .addGroup(panModifierPersonneLayout.createSequentialGroup()
                                        .addComponent(btnSuivant)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnFermerFenetre)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCompteurTotal)))
                .addContainerGap())
        );
        panModifierPersonneLayout.setVerticalGroup(
            panModifierPersonneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panModifierPersonneLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panModifierPersonneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupprimerPersonne)
                    .addComponent(lblCompteur, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompteurTotal)
                    .addComponent(lblSeparateur))
                .addGap(34, 34, 34)
                .addGroup(panModifierPersonneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdPersonne)
                    .addComponent(txtIdPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panModifierPersonneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomPersonne)
                    .addComponent(txtNomPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panModifierPersonneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrenomPersonne)
                    .addComponent(txtPrenomPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panModifierPersonneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panModifierPersonneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDateNaissance)
                    .addComponent(txtDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panModifierPersonneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrganisation)
                    .addComponent(txtOrganisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblObservations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panModifierPersonneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFermerFenetre)
                    .addComponent(btnSuivant)
                    .addComponent(btnPrecedent))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panModifierPersonne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panModifierPersonne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFermerFenetreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerFenetreActionPerformed
        this.i = -1;
        this.dispose();
    }//GEN-LAST:event_btnFermerFenetreActionPerformed

    private void btnSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantActionPerformed
        int maxi;
        maxi = lb.size()-1;        
        if ( this.i < maxi -1 )
        {
            this.i += 1;
        }else{
            this.i = maxi;
        }
        
        
        Personne unePersonne = lb.get(this.i);
        this.numPersonne = unePersonne.getNumPers();
        this.nom_pers = unePersonne.getNomPers();
        this.prenom_pers = unePersonne.getPrenomPers(); 
        this.email_pers = unePersonne.getEmailPers();
        this.date_naiss = unePersonne.getDateNaissancePers();
        this.organisation = unePersonne.getOrganisationPers();
        this.observations = unePersonne.getObservationPers();
        
        lblCompteur.setText(this.i+1 + "");
        txtIdPersonne.setText(String.valueOf(this.numPersonne));
        txtNomPersonne.setText(this.nom_pers);
        txtPrenomPersonne.setText(this.prenom_pers);
        txtEmail.setText(this.email_pers);
        txtDateNaissance.setText(this.date_naiss);
        txtOrganisation.setText(this.organisation);
        txtaObservations.setText(this.observations);
        
        
    }//GEN-LAST:event_btnSuivantActionPerformed

    private void btnPrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedentActionPerformed
        if ( this.i > 0 )
        {
            this.i -= 1;
        }else{
            this.i = 0;
        }
        
        Personne unePersonne = lb.get(this.i);
        this.numPersonne = unePersonne.getNumPers();
        this.nom_pers = unePersonne.getNomPers();
        this.prenom_pers = unePersonne.getPrenomPers(); 
        this.email_pers = unePersonne.getEmailPers();
        this.date_naiss = unePersonne.getDateNaissancePers();
        this.organisation = unePersonne.getOrganisationPers();
        this.observations = unePersonne.getObservationPers();
        
        lblCompteur.setText(this.i+1 + "");
        txtIdPersonne.setText(String.valueOf(this.numPersonne));
        txtNomPersonne.setText(this.nom_pers);
        txtPrenomPersonne.setText(this.prenom_pers);
        txtEmail.setText(this.email_pers);
        txtDateNaissance.setText(this.date_naiss);
        txtOrganisation.setText(this.organisation);
        txtaObservations.setText(this.observations);
    }//GEN-LAST:event_btnPrecedentActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        controleurPersonne pPersonne = new controleurPersonne();
        Personne p = lb.get(this.i);
        //Si réponse = OUI alors n = 0 sinon n=0
        int n = JOptionPane.showConfirmDialog(this,
        "Voulez vous vraiment supprimer " +lb.get(i).getNomPers()+" ?",
        "",JOptionPane.YES_NO_OPTION);
        if(n == 0)
        {
            pPersonne.personneSuppressionBase(p);
            JOptionPane.showMessageDialog(this, "La personne a été supprimée de la BDD !", "Suppression effectué", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSupprimerPersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSupprimerPersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSupprimerPersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSupprimerPersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameSupprimerPersonne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFermerFenetre;
    private javax.swing.JButton btnPrecedent;
    private javax.swing.JButton btnSuivant;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCompteur;
    private javax.swing.JLabel lblCompteurTotal;
    private javax.swing.JLabel lblDateNaissance;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblIdPersonne;
    private javax.swing.JLabel lblNomPersonne;
    private javax.swing.JLabel lblObservations;
    private javax.swing.JLabel lblOrganisation;
    private javax.swing.JLabel lblPrenomPersonne;
    private javax.swing.JLabel lblSeparateur;
    private javax.swing.JLabel lblSupprimerPersonne;
    private javax.swing.JPanel panModifierPersonne;
    private javax.swing.JTextField txtDateNaissance;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdPersonne;
    private javax.swing.JTextField txtNomPersonne;
    private javax.swing.JTextField txtOrganisation;
    private javax.swing.JTextField txtPrenomPersonne;
    private javax.swing.JTextArea txtaObservations;
    // End of variables declaration//GEN-END:variables
}
