/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package annuaire.view;

import annuaire.controleur.controleurPersonne;
import annuaire.dao.daoPersonne;
import annuaire.metier.Personne;
import java.util.ArrayList;

/**
 *
 * @author anthony
 */
public class FrameGestionPersonnes extends javax.swing.JFrame {

    /**
     * Creates new form FrameGestionPersonnes
     */
    public FrameGestionPersonnes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panGestionPersonnes = new javax.swing.JPanel();
        lblGestionPersonnes = new javax.swing.JLabel();
        btnFermer = new javax.swing.JButton();
        btnCreerPersonne = new javax.swing.JButton();
        btnSupprimerPersonne = new javax.swing.JButton();
        btnModifierPersonne = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panGestionPersonnes.setBackground(new java.awt.Color(153, 0, 0));

        lblGestionPersonnes.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblGestionPersonnes.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionPersonnes.setText("Gestion Personnes");

        btnFermer.setText("Fermer cette fenêtre");
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });

        btnCreerPersonne.setText("Créer Personne");
        btnCreerPersonne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreerPersonneActionPerformed(evt);
            }
        });

        btnSupprimerPersonne.setText("Supprimer Personne");
        btnSupprimerPersonne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerPersonneActionPerformed(evt);
            }
        });

        btnModifierPersonne.setText("Modifier Personne");
        btnModifierPersonne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierPersonneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panGestionPersonnesLayout = new javax.swing.GroupLayout(panGestionPersonnes);
        panGestionPersonnes.setLayout(panGestionPersonnesLayout);
        panGestionPersonnesLayout.setHorizontalGroup(
            panGestionPersonnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panGestionPersonnesLayout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(panGestionPersonnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panGestionPersonnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panGestionPersonnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnModifierPersonne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSupprimerPersonne, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(btnCreerPersonne, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panGestionPersonnesLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblGestionPersonnes, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(93, 93, 93))
        );
        panGestionPersonnesLayout.setVerticalGroup(
            panGestionPersonnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGestionPersonnesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblGestionPersonnes)
                .addGap(61, 61, 61)
                .addComponent(btnCreerPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnModifierPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnSupprimerPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnFermer)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panGestionPersonnes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panGestionPersonnes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFermerActionPerformed

    private void btnCreerPersonneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreerPersonneActionPerformed
        FrameCreerPersonne fen = new FrameCreerPersonne();    //Création de l'objet
        fen.setResizable(false);    //Pas de redimensionnement de la fenétre possible.
        fen.setLocationRelativeTo(null);    //Fenêtre centrée au centre 
        fen.setVisible(true);   //Afficher la fenêtre
    }//GEN-LAST:event_btnCreerPersonneActionPerformed

    private void btnModifierPersonneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierPersonneActionPerformed
        FrameModifierPersonne fen = new FrameModifierPersonne();    //Création de l'objet
        fen.setResizable(false);    //Pas de redimensionnement de la fenétre possible.
        fen.setLocationRelativeTo(null);    //Fenêtre centrée au centre 
        fen.setVisible(true);   //Afficher la fenêtre
    }//GEN-LAST:event_btnModifierPersonneActionPerformed

    private void btnSupprimerPersonneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerPersonneActionPerformed
        FrameSupprimerPersonne fen = new FrameSupprimerPersonne();    //Création de l'objet
        fen.setResizable(false);    //Pas de redimensionnement de la fenétre possible.
        fen.setLocationRelativeTo(null);    //Fenêtre centrée au centre 
        fen.setVisible(true);   //Afficher la fenêtre
    }//GEN-LAST:event_btnSupprimerPersonneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGestionPersonnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGestionPersonnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGestionPersonnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGestionPersonnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameGestionPersonnes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreerPersonne;
    private javax.swing.JButton btnFermer;
    private javax.swing.JButton btnModifierPersonne;
    private javax.swing.JButton btnSupprimerPersonne;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblGestionPersonnes;
    private javax.swing.JPanel panGestionPersonnes;
    // End of variables declaration//GEN-END:variables
}
