/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package annuaire.view;

import annuaire.controleur.controleurEnsemble;
import annuaire.dao.daoColloque;
import annuaire.dao.daoPersonne;
import annuaire.metier.Colloque;
import annuaire.metier.Personne;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author anthony
 */
public class FrameInscrire extends javax.swing.JFrame {
    daoPersonne dao = new daoPersonne();
    daoColloque daoC = new daoColloque();
    
    ArrayList<Personne> lb = new ArrayList<Personne>();
    ArrayList<Colloque> lc = new ArrayList<Colloque>();
    /**
     * Creates new form FrameInscrire
     */
    
    int count;
    public FrameInscrire() {
        lb = dao.getALL();
        lc = (ArrayList<Colloque>) daoC.getALL();
        
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblInscription = new javax.swing.JLabel();
        btnFermer = new javax.swing.JButton();
        lblInfo1 = new javax.swing.JLabel();
        lblInfo2 = new javax.swing.JLabel();
        cmbPersonne = new javax.swing.JComboBox();
        cmbColloque = new javax.swing.JComboBox();
        btnInscrire = new javax.swing.JButton();
        lblInfoPlace = new javax.swing.JLabel();
        lblSlash = new javax.swing.JLabel();
        lblPlaceMax = new javax.swing.JLabel();
        lblPlaceRestante = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        lblInscription.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblInscription.setForeground(new java.awt.Color(255, 255, 255));
        lblInscription.setText("Inscription a une colloque");

        btnFermer.setText("Fermer cette fenêtre");
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });

        lblInfo1.setText("Quel personne :");

        lblInfo2.setText("Quel colloque :");

        cmbPersonne.setModel(new javax.swing.DefaultComboBoxModel());
        for (Personne unePersonne : lb)
        {
            cmbPersonne.addItem(unePersonne.getNumPers() + "-" + unePersonne.getNomPers());
        }

        cmbColloque.setModel(new javax.swing.DefaultComboBoxModel());
        for (Colloque unColloque : lc)
        {
            cmbColloque.addItem(unColloque.getNumColloque() +"-"+unColloque.getIntituleColloque());
        }

        btnInscrire.setText("S'inscrire !");
        btnInscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscrireActionPerformed(evt);
            }
        });

        lblInfoPlace.setText("Places disponible pour cette colloque :");

        lblSlash.setText("/");

        lblPlaceMax.setText("jLabel1");

        lblPlaceRestante.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnFermer)
                        .addGap(45, 45, 45))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfo2)
                    .addComponent(lblInfo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnInscrire)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cmbColloque, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbPersonne, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblInfoPlace)
                .addGap(23, 23, 23)
                .addComponent(lblPlaceRestante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSlash)
                .addGap(18, 18, 18)
                .addComponent(lblPlaceMax)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInscription)
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfo1)
                    .addComponent(cmbPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfo2)
                    .addComponent(cmbColloque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfoPlace)
                    .addComponent(lblSlash)
                    .addComponent(lblPlaceMax)
                    .addComponent(lblPlaceRestante))
                .addGap(42, 42, 42)
                .addComponent(btnInscrire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnFermer)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFermerActionPerformed

    private void btnInscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscrireActionPerformed
        controleurEnsemble E = new controleurEnsemble();
        
        int idP,idC; //idPersonne et idColloque
        String SidP; //Valeur de la combo box (String ID Personne)
        String SidC; //Valeur de la combo box (String ID Colloque)
        SidP = cmbPersonne.getSelectedItem().toString();
        SidC = cmbColloque.getSelectedItem().toString();
        String[] tableauP = SidP.split("-");
        String[] tableauC = SidC.split("-");
      
        idP = Integer.parseInt(tableauP[0]);
        idC = Integer.parseInt(tableauC[0]);
        E.Inscrire(idP,idC);
        JOptionPane.showMessageDialog(this, "Enregistrement effectué avec succès !", "Enregistrement effectué", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btnInscrireActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInscrire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInscrire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInscrire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInscrire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInscrire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFermer;
    private javax.swing.JButton btnInscrire;
    private javax.swing.JComboBox cmbColloque;
    private javax.swing.JComboBox cmbPersonne;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInfo1;
    private javax.swing.JLabel lblInfo2;
    private javax.swing.JLabel lblInfoPlace;
    private javax.swing.JLabel lblInscription;
    private javax.swing.JLabel lblPlaceMax;
    private javax.swing.JLabel lblPlaceRestante;
    private javax.swing.JLabel lblSlash;
    // End of variables declaration//GEN-END:variables
}
